### ISSUE TITLE
ENDPOINT /auth

### ISSUE THREAD

**Issue by ManuMarcos** [ElCQ/Apps.-Distribuidas---Grupo-8#5]
Consulta, el endpoint /auth no me deberia devolver los 2 tokens?
![image](https://github.com/ElCQ/Apps.-Distribuidas---Grupo-8/assets/38569631/380eed60-2b12-401b-871a-9ccd53f88f11)
Por que solo devuelve uno que entiendo que es el jwt, pero cuando tengo que renovarlo deberia mandar el refresh token y no lo tengo, entiendo que el diagrama de secuencia a seguir seria este:
![image](https://github.com/ElCQ/Apps.-Distribuidas---Grupo-8/assets/38569631/ed99d24e-42e8-4e79-a527-cd8a0715027c)

**Comment by Nach0Zar** [comment]
En el paso 8 unicamente deberia devolver el nuevo access token ya que el refresh token es el mismo que se envia, no cambia.

**Comment by Nach0Zar** [comment]
Esta seria la respuesta al put de /api/auth
![image](https://github.com/ElCQ/Apps.-Distribuidas---Grupo-8/assets/50642766/2b0abd04-fe2c-4a45-8fe1-0e1c9608bc4d)
